language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
env:
  - DJANGO=django==1.7.10 DRF=3.3.1 DATABASE_URL=mysql://root@localhost/test
  - DJANGO=django==1.7.10 DRF=3.3.1 DATABASE_URL=postgres://postgres@localhost/test
  - DJANGO=django==1.8.6 DRF=3.3.1 DATABASE_URL=mysql://root@localhost/test
  - DJANGO=django==1.8.6 DRF=3.3.1 DATABASE_URL=postgres://postgres@localhost/test
  - DJANGO=https://github.com/django/django/tarball/stable/1.9.x DRF=3.3.1 DATABASE_URL=mysql://root@localhost/test
  - DJANGO=https://github.com/django/django/tarball/stable/1.9.x DRF=3.3.1 DATABASE_URL=postgres://postgres@localhost/test

sudo: false
install:
  - pip install $DJANGO && pip install sphinx argparse coveralls djangorestframework==$DRF
  - if [[ "$DATABASE_URL" == postgres:* ]]; then pip install psycopg2; fi
  - if [[ "$DATABASE_URL" == mysql:* ]]; then pip install mysqlclient; fi
  - python setup.py -q install
before_script:
  - psql -c 'create database test;' -U postgres
  - mysql -e 'create database test character set utf8 collate utf8_general_ci;'
script:
  coverage run --source=hvad --omit='hvad/test*' runtests.py
after_success:
  if [[ $COVERALLS_REPO_TOKEN ]]; then coveralls; fi
matrix:
  exclude:
    - python: 3.3
      env: DJANGO=https://github.com/django/django/tarball/stable/1.9.x DRF=3.3.1 DATABASE_URL=mysql://root@localhost/test
    - python: 3.3
      env: DJANGO=https://github.com/django/django/tarball/stable/1.9.x DRF=3.3.1 DATABASE_URL=postgres://postgres@localhost/test
    - python: 3.5
      env: DJANGO=django==1.7.10 DRF=3.3.1 DATABASE_URL=mysql://root@localhost/test
    - python: 3.5
      env: DJANGO=django==1.7.10 DRF=3.3.1 DATABASE_URL=postgres://postgres@localhost/test
