language: python
python:
  - 2.6
  - 2.7
env:
  - DJANGO_VERSION=1.2.7 ADDITIONAL_PACKAGES='sphinx django-cbv'
  - DJANGO_VERSION=1.3.1 ADDITIONAL_PACKAGES='sphinx'
  - DJANGO_VERSION=1.4 ADDITIONAL_PACKAGES='sphinx'
install:
  - pip install -q Django==$DJANGO_VERSION && pip install $ADDITIONAL_PACKAGES && pip install argparse
  - python setup.py -q install
script: python runtests.py 
