language: python
python:
  - 2.7
  - 3.3
  - 3.4
env:
  - DJANGO=django==1.4.16
  - DJANGO=django==1.4.16 DATABASE_URL=postgres://postgres@localhost/test
  - DJANGO=django==1.5.11
  - DJANGO=django==1.5.11 DATABASE_URL=postgres://postgres@localhost/test
  - DJANGO=django==1.6.8
  - DJANGO=django==1.6.8 DATABASE_URL=postgres://postgres@localhost/test
  - DJANGO=django==1.6.8 DATABASE_URL=mysql://root@localhost/test
  - DJANGO=django==1.7.1
  - DJANGO=django==1.7.1 DATABASE_URL=postgres://postgres@localhost/test
  - DJANGO=django==1.7.1 DATABASE_URL=mysql://root@localhost/test

install:
  - pip install -q $DJANGO && pip install sphinx argparse
  - if [[ "$DATABASE_URL" == postgres:* ]]; then pip install psycopg2; fi
  - if [[ "$DATABASE_URL" == mysql:* ]]; then pip install mysql-python; fi
  - python setup.py -q install
before_script:
  - psql -c 'create database test;' -U postgres
  - mysql -e 'create database test character set utf8 collate utf8_general_ci;'
script: python runtests.py
matrix:
  exclude:
    - python: 3.4
      env: DJANGO=django==1.7.1 DATABASE_URL=mysql://root@localhost/test
    - python: 3.4
      env: DJANGO=django==1.6.8
    - python: 3.4
      env: DJANGO=django==1.6.8 DATABASE_URL=postgres://postgres@localhost/test
    - python: 3.4
      env: DJANGO=django==1.6.8 DATABASE_URL=mysql://root@localhost/test
    - python: 3.4
      env: DJANGO=django==1.5.11
    - python: 3.4
      env: DJANGO=django==1.5.11 DATABASE_URL=postgres://postgres@localhost/test
    - python: 3.4
      env: DJANGO=django==1.4.16
    - python: 3.4
      env: DJANGO=django==1.4.16 DATABASE_URL=postgres://postgres@localhost/test
    - python: 3.3
      env: DJANGO=django==1.7.1 DATABASE_URL=mysql://root@localhost/test
    - python: 3.3
      env: DJANGO=django==1.6.8 DATABASE_URL=mysql://root@localhost/test
    - python: 3.3
      env: DJANGO=django==1.4.16
    - python: 3.3
      env: DJANGO=django==1.4.16 DATABASE_URL=postgres://postgres@localhost/test
